### ISSUE TITLE
tree-sitter version must be bound in requirements.txt

### ISSUE THREAD

**Issue by mahtab-nejati** [GumTreeDiff/tree-sitter-parser#14]
I was trying this parser in a new environment where I installed tree-sitter==0.22.3 on MacOS, but I kept getting the following error:

```
Traceback (most recent call last):
  File "/.../tree-sitter-parser/tree-sitter-parser.py", line 55, in <module>
    main()
  File "/.../tree-sitter-parser/tree-sitter-parser.py", line 41, in main
    parsers = init_parsers(script_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../tree-sitter-parser/tree_sitter_parser/__init__.py", line 22, in init_parsers
    if Language.build_library(
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'tree_sitter.Language' has no attribute 'build_library'
```

My attempt in another environment with tree_sitter==0.20.1 was successful. It might be a good idea to bind the tree-sitter requirement to a specific version. You can see [this discussion](https://github.com/tree-sitter/py-tree-sitter/discussions/241) for more information.

**Comment by mpadge** [comment]
I'm setting the same error, with a few tree_sitter versions between 0.20.1 and 0.22.6, so it doesn't seem directly related to that.

**Comment by jrfaller** [comment]
Thanks for the report. It seems that this function was removed : https://github.com/tree-sitter/py-tree-sitter/pull/145#issuecomment-1969482456 😢 

However, there does not seem to be any replacement... We might have to rethink how we integrate with the Python binding. In the meantime, you can try the Java binding (gen.treesitter-ng).

Cheers.

**Comment by Armorov** [comment]
Good day to all. 

Yeah, like jrfaller say - func was removed (See: https://github.com/tree-sitter/py-tree-sitter/discussions/241).

To use this func you need to downgrade tree-sitter to v0.21. 

It helps me with swift analizing, but I still get some troubles :)

**Comment by jrfaller** [comment]
It's totally possible we do not have a yet a good config for swift ATM!

**Comment by jrfaller** [comment]
BTW @Armorov latest GumTree's commit add swift support to gumtree (using native tree sitter) if you want to try :-)
